
before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"

  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY"
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Use ssh-keyscan to scan the keys of your private server.
  ##
  - ssh-keyscan staging.ourworldmeta.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build-staging:
  stage: build
  tags:
    - gitlab-org-docker
  script:
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - npm install
    - npm run build

test-ssh:
  stage: test
  script:
    - ssh -tt  frontend@staging.ourworldmeta.com echo works! exit

deploy-staging:
  stage: deploy
   needs:
    - job: build
  script:
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i -r dist/* frontend@staging.ourworldmeta.com:/home/frontend/dist
