variables:
  SSH_PRIVATE_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAqsjzUt8JiZ4kCkfB9xgfpSAyMzI/Mx/QVmEGFD+NIRncVHKitvmh
ll3GHEzKEkLW8ojzJDOLvLF3xhkDOct0i9E5EYaW12mfutTD8GM7LoExC7v46vfFn1FsaJ
p+ssA4IzC913tiTfwfTUFJHvCqEq/Qh4GCWaoaEXsJgK0VcH23xjBI0Q3tyH9GMqSfSalt
Xd2ejplrZ2qgEZewpvZybp2DKDBVYmrlb7nYtSLt/m6TgvuMAWoKqGIRC0zpBb5mnuQpuc
v+Ft+uNqLS0flG6IR9+f2DZWRl6S8pW3h0W1/tGp1tPdV63sJNiA1iR+Oryy+lEIF2Eu99
VNojLsNx0+J1h0PoRHpwTFUiicdEuPfX/hhhRPVZIaMGzZ7/bQMMD6hNeRoCzArQ/v/QIB
1RXM9OGBZJW2a+k3zd748DUDPm+xaXFeMWoiYqcFtjiy3bvP+lNhD/eKiOU7c8Y6BtIEGv
ulsVzQYx76fclp1rX/ZuvL+ktSTnz/zmAVZ3H4+K47T3yMhgMqbsQKB96VTNjkej4n62kT
D6Fyze9pq9/7G2EoWDxYvG8/DqPRc1Mh76ghgYlzGOIbiaI1cSZ/GE/KHyn6aXacc5/juO
n8GYcHXDbykRUfsinQwNX/Y2jRJkYar5qwcJO+lht+Ke8tN2Ij7dQbxH+XP61uezApS4SQ
cAAAdYx5IdwceSHcEAAAAHc3NoLXJzYQAAAgEAqsjzUt8JiZ4kCkfB9xgfpSAyMzI/Mx/Q
VmEGFD+NIRncVHKitvmhll3GHEzKEkLW8ojzJDOLvLF3xhkDOct0i9E5EYaW12mfutTD8G
M7LoExC7v46vfFn1FsaJp+ssA4IzC913tiTfwfTUFJHvCqEq/Qh4GCWaoaEXsJgK0VcH23
xjBI0Q3tyH9GMqSfSaltXd2ejplrZ2qgEZewpvZybp2DKDBVYmrlb7nYtSLt/m6TgvuMAW
oKqGIRC0zpBb5mnuQpucv+Ft+uNqLS0flG6IR9+f2DZWRl6S8pW3h0W1/tGp1tPdV63sJN
iA1iR+Oryy+lEIF2Eu99VNojLsNx0+J1h0PoRHpwTFUiicdEuPfX/hhhRPVZIaMGzZ7/bQ
MMD6hNeRoCzArQ/v/QIB1RXM9OGBZJW2a+k3zd748DUDPm+xaXFeMWoiYqcFtjiy3bvP+l
NhD/eKiOU7c8Y6BtIEGvulsVzQYx76fclp1rX/ZuvL+ktSTnz/zmAVZ3H4+K47T3yMhgMq
bsQKB96VTNjkej4n62kTD6Fyze9pq9/7G2EoWDxYvG8/DqPRc1Mh76ghgYlzGOIbiaI1cS
Z/GE/KHyn6aXacc5/juOn8GYcHXDbykRUfsinQwNX/Y2jRJkYar5qwcJO+lht+Ke8tN2Ij
7dQbxH+XP61uezApS4SQcAAAADAQABAAACABQi00WPFIHMSnWH1l+60WhXrnOI1hjCBH9a
uyvB/nLLqMWwKm0ma53d+pC1oRGcHdnEud4n0a7ywatyoYW77kbZ6T+evcQyKOoPUfbSzF
SEWPMIO6YAhqVtJToEFTIgJb5IbemtG38UXeBu9R8XwwWnAxAm/eZyftZWyl0Ii0GTIQrW
AI/dc46zKuSnsjwuJL3vdlVb02UDFlJcrzBQWFegbKldYYPUFK8im2Fn9+WKxguoeu5jwV
PvFBFgBQ1vUIwlXKISYifyQYkhk3e8S1b44B2MfWSD/NwMenTVc+qeGceMjie/Nthy0k9b
PJ47QrMXMAANM42x/PX3LjTCSHZAq3zMZuUYiW28HgiWppucoY0TpVA4p84JdysnSyJk5P
PSmUuPsjl3x4YUQkr9Ijb8cDnrzFL0Q7i20u4s25mr7oyUXWYEl5cBj71/DTTNX9MUbLmc
JjnM6rB4OS6RrMAXddoqEHFLj9jvBqtIT6603x1ylcYqn+jlWsxt8q1BXjjceodAwZ3SS+
I6n81hNCxRlAgXEN0HHKKVwQ43CsFkn6bNO9Gzm8jv7vtMh897+oa0WZBUFR+hz8QfZGwY
xBEgR2YlCclN46Kfl+YMNjTAR+zb7ZllQOeaZpsBLszMCBdiOkFNHEORCAfXWBLxR203cn
CsgOW3ns8wAetQjCk5AAABAHamIdOUqWdiHaY7tbUoGtNAAEHSXnsCUSE4nkkk18Tbq4Q4
NT/PyK1yS1MCNUwy0QxzreqjY4mOfE+vrNOxlvYOV+S9W+gdobCqPbzlD9biWt72O+F6OA
lqXAZKNlC3Hd6Iqea8jLWo2JkzLf8el1T9A+I1GzU5doDP7QVeEyM2HNnauPtkV+Qm1r+L
KvMvMUcxeBP3s3PAAx3JkdUIvjpdLilMiBL8ylFbviV39PmP3vjzItubSmpzrdD//g9qcr
KsUK01hsSrydf5/rGwmsuwBOIutNroIwHKwXLqxBjXgRCZ6gj3wAaW3AxT6vO/a7+TiApW
wifhfnTfjgmEBpAAAAEBANHsmvAid1MBqKSBhkGoQlRSzZRrwO8Ua6OTcz21qZ0vi8Dpyg
5ooYXYT+tAsQ1kYDMOzok+V6uR+lx+3Ni2TP0ZjSHVgitT/zvFM7oTiuXirsI2D17KUkq7
I/ZIGnhji2dr9vAYdl5Ie3oSOvQ6YRw44IYLugqIVstWYPdvwObcdKs3Fa3TuwVtSAiXuj
mSmw9KlYSQcKyOVBOLetgRGDt9XDzEfYEPcIDOXVS/MsYcv/LE7SuxbBnqu7yVJ0K8PIZQ
lKLVDz8icmK2C82nNqUb8XHfi2bYn7BSUlxG9OMkFs3pWmHx/v0l6UEx0vu73zIeakqWxr
GqoXtA0/GOkisAAAEBANBFJ9VbRSOBYd/hfuClw7FMFQK0J0sDdDEKTwA9N5X9F4xxKaD2
Q3/vk+Mmd8tnqlNR3JVqvK3/vXPfSdkx3G8EirddrPawMirPSTGKLujmhUUYBD6WW03wbZ
QKbILv6bnl4jttV1GArbKfxmiFi07FCkDYiJcsXmpS574tIcNvYO8zxWHiFzlG5Y9ARBPs
WNb/5Gnu3LMlb5jTEgEgpeJCRc9FGRTnqs5vMJTNqRUDtBHFWIiMHLlxBaGPqDWnQky3ES
EdfAmRe6N9DM9CIcd84WkOrgBRYe7B3VZKLJT/tQlWkUVCJxzy7JF1y4v6lcfx01Z5GdPj
YY9DQjO6opUAAAAfZnJvbnRlbmRAb3Vydy0xdi0yZy1hbWQtZnJhMS0wMQECAwQ=
-----END OPENSSH PRIVATE KEY-----"


Test SSH:
  script:
    # try to connect to GitLab.com
    - ssh  frontend@staging.ourworldmeta.com

build-job:
  stage: build
  tags:
    - gitlab-org-docker
  script:
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - npm install
    - npm run build
    - echo $SSH_PRIVATE_KEY > id_rsa
    - ls
    # - ssp -i id_rsa frontend@staging.ourworldmeta.com

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
