before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
  - eval $(ssh-agent -s)

  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

Test SSH:
  script:
    # try to connect to GitLab.com
    - ssh frontend@staging.ourworldmeta.com

build-job:
  stage: build
  tags:
    - gitlab-org-docker
  script:
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - npm install
    - npm run build

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
